# Railway configuration file

[build]
  # Define the Dockerfile that Railway will use to build the app
  dockerfile = "Dockerfile"
  # Specify the directory where the Dockerfile is located
  context = "."

[deploy]
  # Specify the service name on Railway
  service = "mvc-app-service"
  startCommand = "dotnet MyMvcApp.dll"
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 5

[deploy.env]
  PORT = "8080"
