# Railway configuration file

[build]
  # Define the Dockerfile that Railway will use to build the app
  dockerfile = "Dockerfile"
  # Specify the directory where the Dockerfile is located
  context = "."

[deploy]
  # Specify the service name on Railway
  service = "mvc-app-service"
  startCommand = "dotnet MyMvcApp.dll"
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 5

[deploy.env]
  PORT = "8080"
  ASPNETCORE_URLS = "http://+:8080"
  ASPNETCORE_ENVIRONMENT = "Production"

  # PostgreSQL Configuration
  PGHOST = "postgres.railway.internal"
  PGPORT = "5432"
  PGDATABASE = "railway"
  PGUSER = "postgres"
  POSTGRES_DB = "railway"
  POSTGRES_USER = "postgres"

  # Note: PGPASSWORD and POSTGRES_PASSWORD are automatically injected by Railway
  DATABASE_URL = "postgresql://postgres:${PGPASSWORD}@postgres.railway.internal:5432/railway"
